/*
USE [MASTER]
GO

DROP DATABASE [TEST]
GO
*/
CREATE DATABASE [TEST]
GO

USE [TEST]
GO

CREATE TABLE [dbo].[MONEDA](
	[CODIGO] [varchar](3) NOT NULL PRIMARY KEY,
	[NOMBRE] [varchar](50) NOT NULL
)
GO

CREATE TABLE [dbo].[BODEGA](
	[CODIGO] [int] NOT NULL PRIMARY KEY,
	[NOMBRE] [varchar](50) NOT NULL
)
GO

CREATE TABLE [dbo].[SUCURSAL](
	[CODIGO] [int] NOT NULL PRIMARY KEY,
	[NOMBRE] [varchar](50) NOT NULL,
	[CODIGO_BODEGA] [INT] FOREIGN KEY REFERENCES [dbo].[BODEGA]
)
GO

CREATE TABLE [dbo].[PRODUCTO](
	[CODIGO] [varchar](50) NOT NULL PRIMARY KEY,
	[NOMBRE] [varchar](50) NOT NULL,
	[CODIGO_BODEGA] [INT] FOREIGN KEY REFERENCES [dbo].[BODEGA],
	[CODIGO_SUCURSAL] [INT] FOREIGN KEY REFERENCES [dbo].[SUCURSAL],
	[CODIGO_MONEDA] [varchar](3) FOREIGN KEY REFERENCES [dbo].[MONEDA],
	[PRECIO] [FLOAT] NOT NULL,
	[MATERIAL] [varchar](100) NOT NULL,
	[DESCRIPCION] [varchar](1000) NOT NULL,
	[FECHA_CREACION] datetime NOT NULL DEFAULT GETDATE()
)
GO